version: "3.9"
services:
  frontend:
    build: document_service
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: document_service
      dockerfile: worker.Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"